
define({
  root: {
    node_parse_syntax: 'Syntax error in CSS query',
    edit_desc: 'Tweak a page resource',
    edit_manual: 'Edit one of the resources that is part of this page (or maybe any generic web resource?)',
    edit_resource_desc: 'URL to edit',
    edit_pretend: 'Pretend this is an popup editor containing',
    stylizer_desc: 'Edit CSS for a node',
    stylizer_manual: 'Find the CSS rules that affect a node so we can edit them together',
    stylizer_node_desc: 'Node to edit (by CSS expression)',
    stylizer_reply: 'This is where we open a window to edit the styles for: {node}.',
    break_desc: 'Manage breakpoints',
    break_manual: 'Commands to list, add and remove breakpoints',
    breaklist_desc: 'Display known breakpoints',
    breaklist_none: 'No breakpoints set',
    breaklist_intro: 'The following breakpoints are set:',
    breakadd_desc: 'Add a breakpoint',
    breakadd_type_desc: 'Type of breakpoint',
    breakadd_if_desc: 'JS guarding breakpoing',
    breakadd_added: 'Added breakpoint',
    breakdell_desc: 'Remove a breakpoint',
    breakdel_breakid_desc: 'Index of breakpoint',
    breakdel_removed: 'Breakpoint removed',
    step_desc: 'Move the debugger on',
    step_manual: 'When the debugger is stopped, move it to a new place',
    stepup_desc: 'Step out of the current function',
    stepup_manual: 'Move the debug position up one stack frame by running to the end of the current function',
    stepin_desc: 'Step into the current function',
    stepin_manual: 'Move the debug position down one stack frame into the current function call',
    stepnext_desc: 'Step to the next line',
    stepnext_manual: 'Move the debug position to the start of the next line',
    stepon_desc: 'Continue running',
    stepon_manual: 'Resume the debugger running normally',
    stepto_desc: 'Run to the given line',
    stepto_manual: 'Move the debug position to the start of the specified line',
    stepto_line_desc: 'Line to run to',
    step_insult: 'The debugger is not stopped. How do you expect to start it? Duh!',
    highlight_desc: 'Highlight a node',
    highlight_manual: 'Examine the dimensions and essential properties of a node (by CSS query)',
    highlight_node_desc: 'CSS query',
    highlight_reply: 'Pretend the highlighter thing is doing its stuff now.',
    inspect_desc: 'Inspect the CSS for a node',
    inspect_manual: 'Examine the detail of the CSS properties for a node',
    inspect_node_desc: 'CSS query',
    inspect_reply: 'Pretend the style inspector is doing its stuff now.',
    doctor_desc: 'Open CSS Doctor for a node',
    doctor_manual: 'Diagnose why a CSS rule isn\'t working for an element',
    doctor_node_desc: 'CSS query',
    doctor_reply: 'Pretend the CSS Doctor is doing its stuff now.',
    echo_desc: 'Show a message',
    echo_message_desc: 'Message',
    console_desc: 'Commands to control the console',
    console_manual: 'Filter, clear and close the web console',
    consoleclear_desc: 'Clear the console',
    consoleclear_reply: 'I\'m sorry, Dave, I can\'t let you do that',
    consoleclose_desc: 'Close the console',
    consoleclose_reply: 'A closed console is like a closed mind which is like a closed book which is bad.',
    consolefilter_desc: 'Filter displayed events',
    consolefilter_category_desc: 'Category',
    consolefilter_level_desc: 'Level',
    consolefilter_display_desc: 'Show|Hide',
    consolefilter_reply: 'This needs implementing'
  }
});
