
define({
  root: {
    node_parse_syntax: 'Syntax error in CSS query',
    edit_desc: 'Tweak a page resource',
    edit_manual: 'Edit one of the resources that is part of this page (or maybe any generic web resource?)',
    edit_resource_desc: 'URL to edit',
    edit_pretend: 'Pretend this is an popup editor containing',
    stylizer_desc: 'Edit CSS for a node',
    stylizer_manual: 'Find the CSS rules that affect a node so we can edit them together',
    stylizer_node_desc: 'Node to edit (by CSS expression)',
    stylizer_reply: 'This is where we open a window to edit the styles for: {node}.',
    break_desc: 'Manage breakpoints',
    break_manual: 'Commands to list, add and remove breakpoints',
    breaklist_desc: 'Display known breakpoints',
    breaklist_none: 'No breakpoints set',
    breaklist_intro: 'The following breakpoints are set:',
    breakadd_desc: 'Add a breakpoint',
    breakadd_type_desc: 'Type of breakpoint',
    breakadd_if_desc: 'JS guarding breakpoing',
    breakadd_added: 'Added breakpoint',
    breakdell_desc: 'Remove a breakpoint',
    breakdel_breakid_desc: 'Index of breakpoint',
    breakdel_removed: 'Breakpoint removed',
  },
});
