
define({
  root: {
    node_parse_syntax: 'Erreur de syntaxe dans la requête CSS',
    edit_desc: 'Tweak une ressource page',
    edit_manual: 'Modifier l\'une des ressources qui fait partie de cette page (? ou peut-être une ressource web générique)',
    edit_resource_desc: 'URL à modifier ',
    edit_pretend: 'Imaginez ceci est un éditeur contextuel contenant',
    stylizer_desc: 'Modifier le CSS pour un nœud',
    stylizer_manual: 'Trouver les règles CSS qui affectent un nœud afin que nous puissions les modifier ensemble',
    stylizer_node_desc: 'nœud à modifier (par CSS expression)',
    stylizer_reply: 'C\'est là que nous ouvrons une fenêtre pour éditer les styles de:. {noeud}',
    break_desc: 'Gérer les points de rupture',
    break_manual: 'Commandes pour la liste, ajouter et supprimer des points d\'arrêt',
    breaklist_desc: 'breakpoints Afficher connu',
    breaklist_none: 'Aucun ensemble des points d\'arrêt',
    breaklist_intro: 'Les points d\'arrêt suivants sont fixés: ',
    breakadd_desc: 'Ajouter un point d\'arrêt',
    breakadd_type_desc: 'Type de point d\'arrêt',
    breakadd_if_desc: 'JS gardiennage breakpoing',
    breakadd_added: 'point d\'arrêt ajoutée',
    breakdell_desc: 'Supprimer un point d\'arrêt',
    breakdel_breakid_desc: 'Indice de point d\'arrêt',
    breakdel_removed: 'Breakpoint retiré',
    step_desc: 'Déplacer le débogueur sur',
    step_manual: 'Lorsque le débogueur est arrêté, le déplacer vers un nouveau lieu',
    stepup_desc: 'Sortez de la fonction en cours ',
    stepup_manual: 'Déplacement de la position de débogage jusqu\'à une image pile en exécutant à la fin de la fonction en cours ',
    stepin_desc: 'Entrez dans la fonction en cours ',
    stepin_manual: 'Déplacement de la position de débogage bas d\'une image pile dans l\'appel de fonction en cours ',
    stepnext_desc: 'Step à la ligne suivante',
    stepnext_manual: 'Déplacement de la position de débogage au début de la ligne suivante',
    stepon_desc: 'Continuer l\'exécution',
    stepon_manual: 'Reprendre le débogueur fonctionne normalement',
    stepto_desc: 'Courez à la ligne donnée',
    stepto_manual: 'Déplacement de la position de débogage au début de la ligne spécifiée',
    stepto_line_desc: 'Ligne de courir à',
    step_insult: 'Le débogueur n\'est pas arrêté. Comment voulez-vous pour le lancer? Duh! ',
    highlight_desc: 'Mettre en surbrillance un noeud',
    highlight_manual: 'Examiner les dimensions et les propriétés essentielles d\'un noeud (par requête CSS)',
    highlight_node_desc: 'CSS requête',
    highlight_reply: '. Pretend la chose surligneur fait sa substance maintenant ',
    inspect_desc: 'Inspecter la CSS pour un nœud',
    inspect_manual: 'Examiner le détail des propriétés CSS pour un nœud',
    inspect_node_desc: 'CSS requête',
    inspect_reply: '. Pretend l\'inspecteur de style fait son truc maintenant',
    doctor_desc: 'Docteur Ouvrez CSS pour un nœud',
    doctor_manual: 'diagnostiquer pourquoi une règle CSS n\'travaillant pour un élément',
    doctor_node_desc: 'CSS requête',
    doctor_reply: '. Pretend du Docteur CSS fait son truc maintenant',
    echo_desc: 'Montrer un message',
    echo_message_desc: 'Message',
    console_desc: 'Commandes pour contrôler la console',
    console_manual: 'Filtre, claire et fermez la console Web',
    consoleclear_desc: 'Effacer la console',
    consoleclear_reply: 'J\'suis désolé, Dave, je peux\'t vous laisser faire cela',
    consoleclose_desc: 'Fermez la console',
    consoleclose_reply: 'Une console fermée est comme un esprit fermé qui est comme un livre fermé qui est mauvais.',
    consolefilter_desc: 'filtrer les événements affichés',
    consolefilter_category_desc: 'Catégorie',
    consolefilter_level_desc: 'niveau',
    consolefilter_display_desc: 'Show|Hide',
    consolefilter_reply: 'Cela doit mettre en œuvre'
  }
});
